### ISSUE TITLE
save data not initialised to zero?

### ISSUE THREAD

**Issue by gingerbeardman** [earwig/crater#3]
ROM: Magical Puzzle Popils 

game says backup data is initialised.
edit mode should display a blank canvas ready for a level to be built.
but it displays random tiles.
if I scroll through the 30 editor slots, the game will crash due to the random data.

Have also tried initialising the save data from the game options screen.

<img width="752" alt="screen shot 2017-07-11 at 20 04 07" src="https://user-images.githubusercontent.com/49612/28085595-191f921c-6674-11e7-87a8-5fc08ee5fe55.png">

<img width="752" alt="screen shot 2017-07-11 at 20 04 17" src="https://user-images.githubusercontent.com/49612/28085596-1936d440-6674-11e7-8319-403e50c12c08.png">

**Comment by earwig** [comment]
Thanks for the bug report. I haven't implemented on-cart RAM, so it makes sense that this is happening. Currently working on it.

**Comment by earwig** [comment]
Added cart RAM support and it should work now! I don't have a real copy of this game so I can't be sure of the correct behavior, but I've compared the behavior with CrabEmu and it seems to be doing the right things.

**Comment by gingerbeardman** [comment]
Thanks very much!

**Comment by gingerbeardman** [comment]
In case you're interested, I'm trying to hack this ROM so that it displays step (and sub-step) count at all times, so I can more easily 100% finish it.

Of course, I could hack the save game but I have a different type of fun solving the puzzles and finding the optimal routes!
