### ISSUE TITLE
Disassembly only does first 4KB of data?

### ISSUE THREAD

**Issue by gingerbeardman** [earwig/crater#7]
disassembly seems to only go as far as $0FE for some reason?

```
2421:	ld	(bc), a					; $0FFD:       02
2422:	ld	bc, $0E00				; $0FFE:       01 00 0E
2423: .byte $0D $0C $0B $0A $09 $08 $07 $07 $06 $05 $04 $03 $02 $01 $00 $0F	; $1001
2424: .byte $0E $0D $0C $0B $0A $09 $08 $07 $06 $05 $04 $03 $02 $01 $00 $2A	; $1011
```

[Magical Puzzle Popils.asm.txt](https://github.com/earwig/crater/files/1150446/Magical.Puzzle.Popils.asm.txt)

```
;; GAME GEAR ROM DISASSEMBLY
;; File: Magical Puzzle Popils.gg
;; Generated on Wed Jul 12, 2017 at 11:30:37 by crater 0.1.dev0
;; ----------------------------------------------------------------------------

.rom_size	"128 KB"	; $20000 bytes in 8 banks
.rom_header	$7FF0
.rom_checksum	off
.rom_product	48017		; Tengen/Time Warner
.rom_version	0
.rom_region	6		; GG Export
.rom_declsize	$F		; 128 KB
```

**Comment by earwig** [comment]
This is the same thing as #5; since we don't know what's code and what's data, at the moment we are just hardcoding the beginning as code and the rest as data. It's not supposed to be realistic for now.

**Comment by gingerbeardman** [comment]
OK, thanks!

I've started using Emulicious - but thanks for your work on crater it was a great help!
